apiVersion: v1
kind: Secret
metadata:
  namespace: kwetter
  name: user-service-secret
type: Opaque
stringData:
  QUARKUS_DATASOURCE_JDBC_URL: jdbc:postgresql://user-service-database:5432/user_db
  QUARKUS_DATASOURCE_USERNAME: postgres
  QUARKUS_DATASOURCE_PASSWORD: mysecretpassword
  QUARKUS_DATASOURCE_DB_KIND: postgresql
  QUARKUS_HIBERNATE_ORM_DATABASE_GENERATION: drop-and-create