apiVersion: v1
kind: Service
metadata:
  name: user-service
  namespace: kwetter
  labels:
    app: user-service
    service: user-service
spec:
  selector:
    app: user-service-pod
  ports:
  - protocol: TCP
    name: http
    port: 80
    targetPort: 80
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
  namespace: kwetter
spec:
  replicas: 1
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  selector:
    matchLabels:
      app: user-service-pod
      version: latest
  template:
    metadata:
      labels:
        app: user-service-pod
        version: latest
    spec:
      containers:
      - name: user-container
        image: neuralm.net:7676/user-service-jvm:latest
        imagePullPolicy: Always
        envFrom:
        - secretRef:
            name: user-service-secret
        resources:
          limits:
            memory: 500Mi
            cpu: 500m
        ports:
        - containerPort: 80
      imagePullSecrets:
        - name: mydockercredentials